### ISSUE TITLE
Tensorflow Version

### ISSUE THREAD

**Issue by raakhal-rapolu** [nsu-ai-team/noise_supression#5]
(noise_env) raakhal@raakhal-HP-Pavilion-Laptop-15-cc1xx:~/artivatic/noise_supression/noise_supression$ python enhance_audio.py MER_rohan.wav MER_rohan1.wav 
Using TensorFlow backend.
WARNING: Logging before flag parsing goes to stderr.
W0612 14:19:41.057055 140574799079168 deprecation.py:323] From /home/raakhal/artivatic/environments/noise_env/lib/python3.6/site-packages/tensorflow-2.0.0b0-py3.6-linux-x86_64.egg/tensorflow/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.

    if isinstance(identifier, tf.Optimizer):
AttributeError: module 'tensorflow' has no attribute 'Optimizer'
(noise_env) raakhal@raakhal-HP-Pavilion-Laptop-15-cc1xx:~/artivatic/noise_supression/noise_supression$ B

**Comment by DinoTheDinosaur** [comment]
Hello!

Thank you for your interest. You are right, you have an incompatible version of Tensorflow in your environment. I specified the Tensorflow version in the setup.py file.

Best regards,
Olga Yakovenko
